# Generated by Django 4.1.6 on 2023-05-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '菜单分类',
                'verbose_name_plural': '菜单分类',
                'db_table': 't_food_category',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='food/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.foodcategory')),
            ],
            options={
                'verbose_name': '菜品详情',
                'verbose_name_plural': '菜品详情',
                'db_table': 't_food',
            },
        ),
    ]
