# Generated by Django 4.1.6 on 2023-05-14 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cartitem'),
        ),
    ]
